### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Saadi6** [cbpowell/CPPickerView#10]
Hi there, 

This is a really cool and easy to use horizontal picker view. Another useful feature would be conditional disabling of scrolling in the picker. For example, when certain conditions are true the value is automatically selected in the picker (which you can already do) and the picker becomes disabled or un-scrollable so the user cant change the values till those conditions remain true.

cheers,
Saad

**Comment by cbpowell** [comment]
I just added an `enabled` property (commit 05ffba0642b0e25bf6f0ec976208bc2f85e09cf6), which at least sets the ground work for what you're looking for. 

Having conditional disabling baked into the picker itself seems like it might get a little complex, so I think perhaps the better way to handle it would be to use your delegate to set the `enabled` property when the conditions are met (since the conditions are specific to your application anyway). Hope this helps!

**Comment by Saadi6** [comment]
Works perfectly! Thanks, that is exactly what I was looking for.
